### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by AidanTheJsDev** [ThePoptartCrpr/jscord#2]
### Description

The documentation has nothing but a few examples if this package is discontinued could you please say something about that in the documentation or something?

### Errors

```

```

### Type

**Severity**:

- [ ] Low
- [ ] Medium
- [x ] High

### Versions

* node.js version:

* jscord version:

**Comment by ThePoptartCrpr** [comment]
No idea how you even found this but yes it's very discontinued
